### ISSUE TITLE
Disable renaming for certain extensions

### ISSUE THREAD

**Issue by chiiya** [ben-rogerson/laravel-mix-make-file-hash#2]
`USE CASE`: I want to rename only JS, CSS and image files, specifically not HTML files. I can create a pull request to add an option for this, unless you know of a better way to handle this use case directly in Laravel Mix?

**Comment by ben-rogerson** [comment]
Hi Chiiya, thanks for submitting the issue.

I don't know of a good way to handle it in Laravel Mix so I'll drop this feature in the next release.
Next release will be within a day! 🎉 

The new API for your use case will look like this:

```js
const convertToFileHash = require("laravel-mix-make-file-hash");
convertToFileHash({
  publicPath: "web",
  manifestFilePath: "web/mix-manifest.json",
  fileTypesBlacklist: ["html"],
  keepBlacklistedEntries: true,
  debug: false
}
```

Let me know if you'd like any adjustments 👍

**Comment by ben-rogerson** [comment]
[New version is out](https://github.com/ben-rogerson/laravel-mix-make-file-hash/releases/tag/v2.0.0) - let me know if there's any issues :)

**Comment by chiiya** [comment]
Thanks, it works for my use case now. If I may make a suggestion: I think to account for all possible use cases a more flexible solution would be to use something like [multimatch](https://github.com/sindresorhus/multimatch) to match filenames instead of just extensions, e.g:
```js
convertToFileHash({
  publicPath: "web",
  manifestFilePath: "web/mix-manifest.json",
  blacklist: ["*.html", "some-special-file.jpg"],
}
```

**Comment by ben-rogerson** [comment]
Great idea!
Update to version 2.1.0 for the blacklist globbing. 
It'll take the new config value of 'blacklist' as you've suggested (with fallback to the 'fileTypesBlacklist' value).
