### ISSUE TITLE
Return promise or use synchronous operations

### ISSUE THREAD

**Issue by chiiya** [ben-rogerson/laravel-mix-make-file-hash#3]
`jsonFile.readFile` and `jsonFile.writeFile` are asynchronous operations. I want to do some additional stuff after the `manifest.json` file has been updated. Either a promise should be returned upon completion or failure, or the synchronous methods should be used.

**Comment by ben-rogerson** [comment]
No worries, this will be in the next release.
Usage as follows:

```js
if (mix.inProduction()) {
  mix.version();
  mix.then(async () => {
    const convertToFileHash = require("laravel-mix-make-file-hash");
    const fileHashedManifest = await convertToFileHash({
      publicPath: "web",
      manifestFilePath: "web/mix-manifest.json"
    });
    // Do something here...
  });
}
```
`fileHashedManifest` will contain the contents of the manifest.

Let me know if you'd require any adjustments.

**Comment by ben-rogerson** [comment]
[New version is out](https://github.com/ben-rogerson/laravel-mix-make-file-hash/releases/tag/v2.0.0) - let me know if there's any issues :)

**Comment by chiiya** [comment]
Thanks, works like a charm!
